version: "3.9"

services:
  app1:
    build: app1
    image: ghcr.io/cyanofresh/docker-compose-ga-cache-example_app1
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
  app2:
    build: app2
    image: ghcr.io/cyanofresh/docker-compose-ga-cache-example_app2
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
